### ISSUE TITLE
Combine Hand Finished with Game State

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#109]
1. Add bool to indicating the hand finished in game state.
2. Add settlements to game state.

**Comment by ryan-northplay** [comment]
heya, @mdfeist you guys using slack or some other comms program? 

I wanna contribute and more closely with you guys though I havent really used much Rust before

**Comment by ajstarna** [comment]
hi @ryan-northplay ! We are actually just some friends working on this for fun, so weren't really planning to collaborate with others. Feel free to ask questions (or possibly submit a PR?) but no guarantees we will be responsive sorry! I think we are actually almost "done" what we were hoping to accomplish.

**Comment by ryan-northplay** [comment]
alright is it OK for me to use your poker canvas in own backend?

![image](https://user-images.githubusercontent.com/128016319/229975246-c05621dc-a407-45b7-a497-ac429d757092.png)

**Comment by ryan-northplay** [comment]
mainly to re-use your table/ui (TableCanvas, ReplayHandler, CardCanvas) @ajstarna

**Comment by ajstarna** [comment]
yep go for it @ryan-northplay , we actually just added an explicit MIT license!
