### ISSUE TITLE
can we handle meta actions at least once during the showdown

### ISSUE THREAD

**Issue by ajstarna** [ajstarna/poker#115]
currently since the showdown takes several seconds, meta actions (mainly "Leave") are left hanging for a while
maybe we can handle meta actions before the long sleep, or more than once even

**Comment by mdfeist** [comment]
That is on the server side. I handle leaving as soon as you receive the leave message.

**Comment by mdfeist** [comment]
I think we might need to refactor how the sleep works. Instead of locking the thread for x number of seconds the thread should just wait before performing the next game state. But then still grab meta actions.

**Comment by ajstarna** [comment]
thats why i assigned it to me! :) i would rather not do a massive refactor, so i think ill just add more frequent meta action handles and shorter sleeps

**Comment by ajstarna** [comment]
ok now all sleeps happen in a helper function that loops and checks for meta actions on shorter periods. Feels pretty solid for SitOut and Leave messages
