### ISSUE TITLE
Game Crashing: thread '<unnamed>' panicked at 'dont get in this situation', src/logic/game.rs:79:13

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#15]
Playing hand 6, button_idx = 5
inside of play(). button_idx = 5
players = [Some(Player { id: a1ba00b8-0786-4332-b241-6e144e9efb9a, hole_cards: [], is_active: false, is_sitting_out: false, money: 0, human_controlled: false }), Some(Player { id: 569c93e1-22d5-45cd-8724-47e6a264829b, hole_cards: [Card { rank: Two, suit: Heart }, Card { rank: Queen, suit: Spade }], is_active: true, is_sitting_out: false, money: 996, human_controlled: false }), Some(Player { id: 06990630-f456-4fc0-921e-915723609f47, hole_cards: [], is_active: false, is_sitting_out: false, money: 0, human_controlled: false }), Some(Player { id: 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, hole_cards: [Card { rank: Eight, suit: Heart }, Card { rank: Four, suit: Spade }], is_active: true, is_sitting_out: false, money: 139, human_controlled: false }), Some(Player { id: 62f9fc9d-3b20-48a2-ad98-7b0dd0a9b3e5, hole_cards: [Card { rank: Two, suit: Spade }, Card { rank: Four, suit: Diamond }], is_active: true, is_sitting_out: false, money: 1842, human_controlled: false }), Some(Player { id: 2c473cd3-a1d2-4abd-840d-bc029a5be88b, hole_cards: [Card { rank: King, suit: Heart }, Card { rank: Queen, suit: Diamond }], is_active: true, is_sitting_out: false, money: 1215, human_controlled: false }), Some(Player { id: 5eb01af7-0824-4c9b-b9c1-11a035e921d6, hole_cards: [Card { rank: Jack, suit: Heart }, Card { rank: Eight, suit: Spade }], is_active: true, is_sitting_out: false, money: 4808, human_controlled: false }), Some(Player { id: a742e833-bbfb-4a9b-91d4-b2e66aebb768, hole_cards: [], is_active: false, is_sitting_out: false, money: 0, human_controlled: false }), Some(Player { id: f0241fc7-72d7-4d8a-8969-28aaf739cdf5, hole_cards: [], is_active: false, is_sitting_out: false, money: 0, human_controlled: true })]
Current pot = Some(Pot { money: 0, contributions: {}, cap: None })
num active players = 5
player at index 6 starts the betting
start loop index = 6: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 0, contributions: {}, cap: None }] }, Current size of the bet = 0, and this player has put in 0 so far
Player = 5eb01af7-0824-4c9b-b9c1-11a035e921d6, i = 6
inside contribute: 5eb01af7-0824-4c9b-b9c1-11a035e921d6, 4, all_in=false
no cap
{"index":6,"player_name":"Mr 6","action":"small blind","amount":4,"money":4804,"pots":[4],"is_active":true,"street_contributions":4,"current_bet":4}
start loop index = 7: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 4, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4}, cap: None }] }, Current size of the bet = 4, and this player has put in 0 so far
Player = a742e833-bbfb-4a9b-91d4-b2e66aebb768, i = 7
start loop index = 8: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 4, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4}, cap: None }] }, Current size of the bet = 4, and this player has put in 0 so far
Player = f0241fc7-72d7-4d8a-8969-28aaf739cdf5, i = 8
start loop index = 0: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 4, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4}, cap: None }] }, Current size of the bet = 4, and this player has put in 0 so far
Player = a1ba00b8-0786-4332-b241-6e144e9efb9a, i = 0
start loop index = 1: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 4, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4}, cap: None }] }, Current size of the bet = 4, and this player has put in 0 so far
Player = 569c93e1-22d5-45cd-8724-47e6a264829b, i = 1
inside contribute: 569c93e1-22d5-45cd-8724-47e6a264829b, 8, all_in=false
no cap
{"index":1,"player_name":"Mr 1","action":"big blind","amount":8,"money":988,"pots":[12],"is_active":true,"street_contributions":8,"current_bet":8}
start loop index = 2: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 12, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4, 569c93e1-22d5-45cd-8724-47e6a264829b: 8}, cap: None }] }, Current size of the bet = 8, and this player has put in 0 so far
Player = 06990630-f456-4fc0-921e-915723609f47, i = 2
start loop index = 3: num_active = 5, num_settled = 0, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 12, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4, 569c93e1-22d5-45cd-8724-47e6a264829b: 8}, cap: None }] }, Current size of the bet = 8, and this player has put in 0 so far
Player = 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, i = 3
Attempting to get player action on attempt 0
difference = 52
sup Player { id: 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, hole_cards: [Card { rank: Eight, suit: Heart }, Card { rank: Four, suit: Spade }], is_active: true, is_sitting_out: false, money: 87, human_controlled: false }
inside contribute: 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, 52, all_in=false
no cap
{"index":3,"player_name":"Mr 3","action":"bet","amount":52,"money":87,"pots":[64],"is_active":true,"street_contributions":52,"current_bet":52}
start loop index = 4: num_active = 5, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 64, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52}, cap: None }] }, Current size of the bet = 52, and this player has put in 0 so far
Player = 62f9fc9d-3b20-48a2-ad98-7b0dd0a9b3e5, i = 4
Attempting to get player action on attempt 0
{"index":4,"player_name":"Mr 4","action":"fold","money":1842,"pots":[64],"is_active":false,"street_contributions":0,"current_bet":52}
start loop index = 5: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 64, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52}, cap: None }] }, Current size of the bet = 52, and this player has put in 0 so far
Player = 2c473cd3-a1d2-4abd-840d-bc029a5be88b, i = 5
Attempting to get player action on attempt 0
difference = 257
sup Player { id: 2c473cd3-a1d2-4abd-840d-bc029a5be88b, hole_cards: [Card { rank: King, suit: Heart }, Card { rank: Queen, suit: Diamond }], is_active: true, is_sitting_out: false, money: 958, human_controlled: false }
inside contribute: 2c473cd3-a1d2-4abd-840d-bc029a5be88b, 257, all_in=false
no cap
{"index":5,"player_name":"Mr 5","action":"bet","amount":257,"money":958,"pots":[321],"is_active":true,"street_contributions":257,"current_bet":257}
start loop index = 6: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 321, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 4, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 257, and this player has put in 4 so far
Player = 5eb01af7-0824-4c9b-b9c1-11a035e921d6, i = 6
Attempting to get player action on attempt 0
difference = 832
sup Player { id: 5eb01af7-0824-4c9b-b9c1-11a035e921d6, hole_cards: [Card { rank: Jack, suit: Heart }, Card { rank: Eight, suit: Spade }], is_active: true, is_sitting_out: false, money: 3972, human_controlled: false }
inside contribute: 5eb01af7-0824-4c9b-b9c1-11a035e921d6, 832, all_in=false
no cap
{"index":6,"player_name":"Mr 6","action":"bet","amount":836,"money":3972,"pots":[1153],"is_active":true,"street_contributions":836,"current_bet":836}
start loop index = 7: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1153, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 0 so far
Player = a742e833-bbfb-4a9b-91d4-b2e66aebb768, i = 7
start loop index = 8: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1153, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 0 so far
Player = f0241fc7-72d7-4d8a-8969-28aaf739cdf5, i = 8
start loop index = 0: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1153, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 0 so far
Player = a1ba00b8-0786-4332-b241-6e144e9efb9a, i = 0
start loop index = 1: num_active = 4, num_settled = 1, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1153, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 8, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 8 so far
Player = 569c93e1-22d5-45cd-8724-47e6a264829b, i = 1
Attempting to get player action on attempt 0
Attempting to get player action on attempt 0
new bet must be larger than current
Attempting to get player action on attempt 0
Attempting to get player action on attempt 0
inside contribute: 569c93e1-22d5-45cd-8724-47e6a264829b, 828, all_in=false
no cap
{"index":1,"player_name":"Mr 1","action":"call","amount":828,"money":160,"pots":[1981],"is_active":true,"street_contributions":836,"current_bet":836}
start loop index = 2: num_active = 4, num_settled = 2, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1981, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 836, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 0 so far
Player = 06990630-f456-4fc0-921e-915723609f47, i = 2
start loop index = 3: num_active = 4, num_settled = 2, num_all_in = 0
Current pot = PotManager { pots: [Pot { money: 1981, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 836, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 52, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: None }] }, Current size of the bet = 836, and this player has put in 52 so far
Player = 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, i = 3
Attempting to get player action on attempt 0
you have to put in the rest of your chips
inside contribute: 31ceb4b1-c1e6-40c4-b41f-c210226a1e02, 87, all_in=true
no cap
adding a new pot!
{"index":3,"player_name":"Mr 3","action":"call","amount":87,"money":0,"pots":[2068,0],"is_active":true,"street_contributions":139,"current_bet":836}
start loop index = 4: num_active = 4, num_settled = 2, num_all_in = 1
Current pot = PotManager { pots: [Pot { money: 2068, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 836, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 139, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: Some(139) }, Pot { money: 0, contributions: {}, cap: None }] }, Current size of the bet = 836, and this player has put in 0 so far
Player = 62f9fc9d-3b20-48a2-ad98-7b0dd0a9b3e5, i = 4
start loop index = 5: num_active = 4, num_settled = 2, num_all_in = 1
Current pot = PotManager { pots: [Pot { money: 2068, contributions: {5eb01af7-0824-4c9b-b9c1-11a035e921d6: 836, 569c93e1-22d5-45cd-8724-47e6a264829b: 836, 31ceb4b1-c1e6-40c4-b41f-c210226a1e02: 139, 2c473cd3-a1d2-4abd-840d-bc029a5be88b: 257}, cap: Some(139) }, Pot { money: 0, contributions: {}, cap: None }] }, Current size of the bet = 836, and this player has put in 257 so far
Player = 2c473cd3-a1d2-4abd-840d-bc029a5be88b, i = 5
Attempting to get player action on attempt 0
Attempting to get player action on attempt 0
inside contribute: 2c473cd3-a1d2-4abd-840d-bc029a5be88b, 579, all_in=false
cap of 139
thread '<unnamed>' panicked at 'dont get in this situation', src/logic/game.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ajstarna** [comment]
believe this is fixed in an incoming PR
