### ISSUE TITLE
Sitting Out should still pay the blinds

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#22]
Right now it looks like the person sitting out is being treated as they left the game. However, shouldn't they still be paying the blinds? They are still at the table and shouldn't it be treated as an automatic fold?

Maybe this is different with cash games?

**Comment by ajstarna** [comment]
hmm not sure. i think ur right that for cash games that might not make sense. youre so focused on tournaments lol! We can think about this, but don't consider it urgent to change. Eventually we might simply want cash game versus tourney modes?

**Comment by mdfeist** [comment]
Read this. Currently, it isn't 100% correct for both cash or tournaments.

https://www.casinoanswers.com/online-poker/beginners/sit-out-poker-room.php

**Comment by ajstarna** [comment]
bumping this - i will implement this next. currently you could game the system to sit out during blinds then come back in after ha. edge case but i agree they should pay the blinds

**Comment by ajstarna** [comment]
this is done
