### ISSUE TITLE
Called `Option::unwrap()` on a `None` value', src/logic/game.rs:507:73

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#28]
Setup:

Two player heads up.
Player 1 wins and has all the chips.
Player 1 leaves the table.

thread 'Handling player PlayerConfig { id: b1204cb1-cbb9-44b3-b6c5-aeb094cb3b3f, name: Some("Thanny"), player_addr: Some(Recipient { /* omitted */ }) } removed
<unnamed>' panicked at 'removing player PlayerConfig { id: b1204cb1-cbb9-44b3-b6c5-aeb094cb3b3f, name: Some("Thanny"), player_addr: Some(Recipient { /* omitted */ }) } removed from "GRSD"
called `Option::unwrap()` on a `None` value', src/logic/game.rs:507:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ajstarna** [comment]
i think this was fixed, but lets see lol...
