### ISSUE TITLE
Big blind only has less than big blind

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#61]
If the big blind has less than the required amount the other players still have to call the big blind.

Example:

1. Small Blind (1 chip)
2. Big Blind (All in with 1 chip)
3. Small Blind can't check has to call and is now in for 2 chips.

However in this example the small blind shouldn't have to put in more chips. Also in this case the side pot doesn't seem to work.

**Comment by ajstarna** [comment]
isnt this desired behaviour? the big_blind is the minimum amount anyone needs to put in?

**Comment by ajstarna** [comment]
this should be fixed now, the current bet is only as much as the blind can afford
