### ISSUE TITLE
Table List Add Info

### ISSUE THREAD

**Issue by mdfeist** [ajstarna/poker#63]
For the table list, instead of just returning the table names I would like the following info as well.

1. Big and small blind size
2. Number of players
3. Max number of players
4. Private? If you want to list private games as well.

I am thinking it should return a list of JSON objects like:

```JSON
[
  {
   "table_name": "TEST",
   "small_blind": 1,
   "big_blind": 2,
   "num_of_players": 3,
   "max_players": 9
  },
]
```

**Comment by ajstarna** [comment]
kk will do next. ill also include num_bots i think

**Comment by mdfeist** [comment]
Sure. I was mostly wanting to calculate the number of available seats. Therefore in my mind the number of players included both humans and bots.

**Comment by ajstarna** [comment]
dun
